amirshop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = ([
    url(r'^admin/', admin.site.urls),

])

urlpatterns += i18n_patterns(

    url(r'', include('products.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import *

app_name = 'products'

urlpatterns = [
    url(r'^$', CategoryList.as_view(), name='categories'),
    url(r'^category/(?P<slug>[-\w]+)/$', CategoryDetail.as_view(), name='category_detail'),
    url(r'^login/$', login_user, name='login'),
    url(r'^register/$', UserForm.as_view(), name='register'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^product/(?P<slug>[-\w]+)/$', ProductDetail.as_view(), name='product_detail'),
    url(r'^(?P<slug>[-\w]+)/(?P<user>[-\w]+)/$', comment, name='comment'),
    url(r'^thanks/$', thanks, name='thanks'),

]

products/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.text import slugify
from django.conf import settings


class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300, blank=True)
    slug = models.SlugField(blank=True)

    class Meta:
        order_with_respect_to = 'title'
        verbose_name_plural = "Categories"
        db_table = 'products_categories'

    def __str__(self):
        return u'%s' % self.title

    def clean(self):
        return self.clean_fields()

    def get_absolute_url(self):
        self.slug = slugify(self.title)
        self.save()
        return reverse('products:category_detail', kwargs={'slug': self.slug})


class Merchant(models.Model):
    title = models.CharField(max_length=100)
    logo = models.FileField()


class Product(models.Model):
    title_en = models.CharField(max_length=255, null=False, default=0)
    title_ar = models.CharField(max_length=255, null=True)
    slug = models.SlugField(allow_unicode=True, blank=True)
    specs = JSONField()
    category = models.ForeignKey(Category, default=0)
    merchant = models.ForeignKey(Merchant, null=False, default=0)

    def __str__(self):
        return self.title_en

    def get_absolute_url(self):
        self.slug = slugify(self.title_en)
        self.save()
        return reverse('products:product_detail', kwargs={'slug': self.slug})

    class Meta:
        order_with_respect_to = 'title_en'


class Reviews(models.Model):
    product = models.ForeignKey(Product)
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    comments = models.CharField(max_length=510, null=False, default="")
    approved_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.comments

products/forms.py
from django.contrib.auth.models import User
from .models import Reviews
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
        ]

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = ['comments',
                  ]

products/views.py
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponseRedirect, redirect, get_object_or_404
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import ListView
from amirshop.settings import LANGUAGES
from .models import *
from .forms import UserForm, ReviewForm


# Create your views here.


class UserForm(FormView):
    form_class = UserForm
    template_name = "register.html"


    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/')


class CategoryList(ListView):
    model = Category
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        context['LANGUAGES'] = LANGUAGES
        return context


class CategoryDetail(ListView):
    model = Product
    template_name = "category.html"


class ProductDetail(DetailView):
    model = Product
    template_name = "product_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        context['form'] = ReviewForm()
        return context


def comment(request, slug, user):
    product = get_object_or_404(Product, slug=slug)
    from django.contrib.auth.models import User
    user = get_object_or_404(User, username=user)
    print [user, product]
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = user
            review.product = product
            review.save()

            return HttpResponseRedirect('/thanks/')

    else:
        form = ReviewForm()
        return render(request, 'product_detail.html', {'form': form})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                category = Category.objects.all()
                return render(request, 'index.html', {'object_list': category})
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def thanks(request):
    return render(request, 'thanks.html')

products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block Title %}
        {% endblock %}
    </title>
</head>
<body>

{% block body %}
{% endblock %}
{% block login %}
{% endblock %}
</body>
</html>

products/templates/category.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
    {% for prod in object_list %}
    {% if request.LANGUAGE_CODE == 'en' %}
    <a href="{{ prod.get_absolute_url }}">{{ prod.title_en }}</a>
    {% else %}
    <a href="{{ prod.get_absolute_url }}">{{ prod.title_ar }}</a>
    {% endif %}
{% endfor %}
{% endblock %}

products/templates/detail.html
{% extends "base.html" %}

{% block body %}
    <h2>Products</h2>
    <ul>
        {% for product in object_list %}
            <li>{{ product.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

products/templates/form.html
{% for field in form %}
    <div class="form-group">
        <div>
            <span>{{ field.errors }}</span>
        </div>
        <div>{{ field }}</div>
    </div>
{% endfor %}

products/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}home{% endblock %}
{% block body %}
{% for lang in LANGUAGES %}
    <a href="/{{ lang.0 }}/">{{ lang.1 }}</a>
    {% endfor %}
 {% if request.user.is_authenticated %}

    <h3><strong>{% trans "Welcome" %} {{ request.user }}</strong></h3>
    <a type="button" href="{% url 'products:logout' %}">logout</a>
{% else %}
     <a type="button" href="{% url 'products:login' %}">Login</a>
     <a type="button" href="{% url 'products:register' %}">Register</a>
{% endif %}
<hr>


{% for cat in object_list %}
<a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>
    <br><hr width="300px" style="float: left">
{% endfor %}
{% endblock %}

products/templates/list.html
{% extends "base.html" %}

{% block body %}
    <h2>Products</h2>
    <ul>
        {% for product in object_list %}
            <li>{{ product.title }}</li>
        {% endfor %}
    </ul>
{% endblock %}

products/templates/login.html
{% extends 'base.html' %}
{% block title %}login{% endblock %}

{% block login %}


<h3>Log In</h3>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form role="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <label for="id_username">
            Username:
        </label>
            <input maxlength="30" name="username" type="text">
        <label for="id_password">
            Password:
        </label>
            <input maxlength="30" name="password" type="password">
            <button type="submit" >Submit</button>
</form>

Don't have an account? <a href="{% url 'products:register' %}">Click here</a> to register.

{% endblock %}

products/templates/product_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}


    {% if request.LANGUAGE_CODE == 'en' %}
        {{ product.title_en }}

    {% else %}
        {{ product.title_ar }}

    {% endif %}
    {% if user.is_anonymous %}
        <h5>Sorry you have to <a href="{% url 'products:login' %}">login </a> to comment</h5>
    {% else %}


    <hr>
{% endif %}
    {% if user.reviews.product != product %}
        <form method="POST" action="{% url 'products:comment' slug=product.slug user=request.user %}">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Submit">
        </form>
    {% endif %}
    {% for comment in product.reviews_set.all %}

        {% if comment.approved_comment == True %}

            <div>{{ comment.user }}</div>
            <strong>{{ comment.comments }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        {% elif comment.approved_comment == False and comment.user == request.user %}
            Your comment is under review

        {% endif %}


    {% empty %}

        <p>No comments here yet :(</p>

    {% endfor %}

{% endblock %}

products/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block login %}

                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>Error</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'products:register' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form.html' %}
                                <button type="submit">Submit</button>

                    </form>

                    Already have an account? <a href="{% url 'products:login' %}">Click here</a> to log in.


{% endblock %}

products/templates/thanks.html
{% extends "base.html" %}

{% block body %}
    <h2>Thanks</h2>

{% endblock %}